module.exports = function(wss) {
	var Message = require('mongoose').model('Message');
	var Chat = require('mongoose').model('Chat');
	var reqError = require('../common/reqError.js');
	var webSocketScript = require('../../config/websocket.js');
	//const wss = require('../../config/websocket.js').getwss();

	var c = {};

	c.create = function(req, res) {
		console.log(JSON.stringify(req.body));

		// want to use the id generated by mongo
		delete req.body._id

		// perform a query to get the id of the chat from the name
		var chatQ = Chat.findOne({name : req.body.chat}, "-__v");

		chatQ.exec(function(err, chat) {
			if (err) return reqError(res, 500, err);
			console.log(JSON.stringify(chat));

			var newMessageObj = {
				handle : req.body.handle,
				message : req.body.message,
				date : new Date(),
				chat : chat._id
			}

			var newMessage = new Message(newMessageObj);

			newMessage.save(function(err) {
				if (err) return reqError(res, 500, err);
				
				newMessage.populate('chat', function(err, newMessage) {
					if (err) return reqError(res, 500, err);
					// on a successfule save to the database, send the message through websockets
					// this way message will appear in clients without calling a GET request from the client
					//webSocketScript.send(wss, newMessageObj);

					console.log("new message " + newMessage);
					webSocketScript.send(wss, newMessage);

					res.status(201).json({
						newMessage : newMessage
					});
				});
				
			});
		});
	}

	c.getAll = function(req, res) {
		var q = Message.find({});
		q.sort('date');
		q.exec(function(err, messages) {
			if (err) return reqError(res, 500, err);

			res.json(messages);
		});
	}

	c.getByChat = function(req, res) {
		var chat_name = req.params.chat_name;
		var q = Chat.findOne({name : chat_name}, "-__v");
		q.exec(function(err, chat) {
			if (err) return reqError(res, 500, err);
			console.log("chat id " + chat._id);
			var q = Message.find({chat : chat._id});
			q.populate({ path : 'chat' });
			q.sort('date');
			q.exec(function(err, messages) {
				if (err) return reqError(res, 500, err);
				console.log("messages for chat " + chat_name + messages);
				res.json(messages);
			});
		});
	}

	return c;
}